name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  BACKEND_IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/pern-todo-app-server
  FRONTEND_IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/pern-todo-app-client
  DATABASE_IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/pern-todo-app-db

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install server dependencies
        run: |
          cd server
          npm ci

      - name: Install client dependencies
        run: |
          cd client
          npm ci

      - name: Run server tests (if any)
        run: |
          cd server
          npm test --if-present

      - name: Run client tests
        run: |
          cd client
          npm test --if-present --watchAll=false

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Build and push server image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.server
          push: true
          tags: ${{ env.BACKEND_IMAGE_NAME }}:latest,${{ env.BACKEND_IMAGE_NAME }}:${{ github.sha }}

      - name: Build and push client image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.client
          push: true
          tags: ${{ env.FRONTEND_IMAGE_NAME }}:latest,${{ env.FRONTEND_IMAGE_NAME }}:${{ github.sha }}

      - name: Build and push database image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.db
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-db:${{ steps.meta.outputs.version }}
          labels: ${{ steps.meta.outputs.labels }}

  # deploy:
  #   needs: build-and-push
  #   runs-on: ubuntu-latest
  #   if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    
  #   steps:
  #     - name: Deploy to production
  #       run: |
  #         echo "Deployment step - Add your deployment logic here"
  #         echo "For example: deploy to cloud platform, update production environment, etc." 