name: Deploy to Production

on:
  workflow_run:
    workflows: ["CI/CD Pipeline"]
    types:
      - completed
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Deploy to production server
        run: |
          echo "Deploying to production..."
          echo "Add your deployment commands here"          
          echo "Deployment completed successfully!"

      - name: Health check
        run: |
          echo "Running health checks..."